---

- hosts: all
  become: yes
  gather_facts: no
  remote_user: vagrant

  tasks:

  - name: Distribute SSH key for user "vagrant"
    authorized_key:
      user: vagrant 
      key: "{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}" 
      state: present
